networks:
  inception:
    driver: bridge
    
services:
  nginx:
    networks:
      - inception
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}
    ports:
    - "443:443"
    restart: on-failure

  wordpress:
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
  wordpress_data: