services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}
    ports:
    - "443:443"
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        ALPINE_IMAGE: ${ALPINE_IMAGE}